# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-396f7a88-8804-4cc9-ba70-316e03fa5392";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-396f7a88-8804-4cc9-ba70-316e03fa5392".device = "/dev/disk/by-uuid/396f7a88-8804-4cc9-ba70-316e03fa5392";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4D7E-0688";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-86629040-9218-488a-bec6-dffb2dd88f45"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
